### ISSUE TITLE
variablenfehler

### ISSUE THREAD

**Issue by dav22297** [Phylex/praktikumsauswertung#1]
Soll eine weitere Messgroesse eingestellt werden(y/n):n
[['Kraft', 'N', 'Messuhr bliblablub', 1, -2.0], ['Stecke', 'm', 'ikea lineal', -3, 0.5]]

Traceback (most recent call last):
  File "Messen.py", line 94, in <module>
    del aktuelle_messgroesse
NameError: name 'aktuelle_messgroesse' is not defined

**Comment by GalaxG64** [comment]
Hab ich gleich gemacht

**Comment by GalaxG64** [comment]
behoben
